### ISSUE TITLE
seed problem

### ISSUE THREAD

**Issue by WeCcRy** [AdityaLab/pinnsformer#7]
it's too hard to find a seed to make the network work. To be honest, it's hard to figure out whether the optimization is caused by the network or the seed. The idea of using transformer is a good one, but whether it works or not needs to be discussed. I also hope that  someone could provide seeds that will perform well on 4090 or A100.

**Comment by tsano430** [comment]
There are similar issues:

- https://github.com/AdityaLab/pinnsformer/issues/5
- https://github.com/AdityaLab/pinnsformer/issues/6

**Comment by leozhao1997** [comment]
Added the [checkpoints ](https://github.com/AdityaLab/pinnsformer/tree/main/checkpoint) hopefully helps.

While we fix the random seed, the results can still vary due to different versions of dependencies and Cuda versions. It may be worth some hyperparameter tuning if it does not exhibit the desirable results.
